version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: pulumi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
